### PR TITLE
MIlestone 5

### PR DESCRIPTION
**Pull request by bertil291utn**
# Hey guys, we'd appreciate if you help us with some feedback

We accomplished these requirements, [Friendship v1 ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)

>Add a friendship model and methods to the user model

A new Friendship model which connects users with other
users' friends. In Addition, the next methods were added to the user
model:
* friends
* pending_friends
* friend_requests
* confirm_friend
* friend?
<hr>
We thank you in beforehand 💻 🚀

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @bertil291utn and @meme-es  :balloon: :lollipop: 

### Thank you for your submission :medal_sports: :medal_sports:  I see you've added all the required changes to the User and Friendship models to properly have friendships :ok_hand: :ok_hand:  and also added unit test cases for friendships and this wasn't required but you added both unit and integration test cases for the functionality that came with the repo so claps to you for that :clap: :clap: but there is still important work to do with the controllers, views, and integration test cases for Friendships :construction: :construction_worker: :construction_worker: 

## Milestone 5 Friendships v1. missing requirements
#### Controlers and Views:
Everything works in the console but please add all the buttons, controllers, helpers or partials necessary to make the following work in the web application: 
* [x] There is a button to invite a user to friendship on the All Users page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

## Test cases
for every scenario that can exist in the web application, there should be an integration test but for this milestone, in particular, it was only required to have test cases for the Friendship scenarios

* [x] Add integration test cases for this milestone ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) take into account the following scenarios:
  - Send friend request from Users index page
  - Send friend request from Users show page
  - Accept friendship
  - Decline friendship
  - See posts from the user and his or her friends in the Timeline'

### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,
Thank you for the suggested changes implemented :smile: It's a big improvement :+1: 
However, there are still some changes to do

1. After requesting a friendship, here is what I have on **All Users** page
Screenshot at 2020-06-02 07:57:12

You will notice the existence of a link for **inviting the user to friendship** with a link **to accept/reject** the friendship sent to him. Does it sound good?
Here is what the database contains when I click on **Invite to friendship**
```rb
2.7.0 :001 > Friendship.all
Friendship Load (0.7ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 3, user_id: 2, friend_id: 1, confirmed: false, created_at: "2020-06-02 07:00:11", updated_at: "2020-06-02 07:00:11">, #<Friendship id: 4, user_id: 1, friend_id: 2, confirmed: false, created_at: "2020-06-02 07:00:31", updated_at: "2020-06-02 07:00:31">]> 
2.7.0 :002 > 
```
And if I click on **Accept the friendship**, I got this
```rb
2.7.0 :001 > Friendship.all
  Friendship Load (0.7ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 4, user_id: 1, friend_id: 2, confirmed: false, created_at: "2020-06-02 07:00:31", updated_at: "2020-06-02 07:00:31">, #<Friendship id: 3, user_id: 2, friend_id: 1, confirmed: true, created_at: "2020-06-02 07:00:11", updated_at: "2020-06-02 07:05:01">]> 
2.7.0 :002 > 
```
The result means that there is a Friendship relation between `user 2` and `user 1` and at the same time that there is not a friendship between `user 2` and `user 1`. Does it sound good?

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by bertil291utn** [comment]
# @maelfosso  Thank you for the code review.
1. Certainly the view with an **invitation to friendship | Accept | Reject** is not a great achievement we are going to change just to display accept and reject buttons.

<hr>

Thank you  💻 🚀 🤘

**Comment by maelfosso** [comment]
You are welcome @bertil291utn

**Pull request closed without merging**
